name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/docker-publish.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gitlab-badge-api:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/gitlab-badge-api:${{ github.event.inputs.version }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gitlab-badge-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gitlab-badge-api:${{ github.event.inputs.version }}
